version: '3.7'

services:
  web:
    build: ./assistans
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./assistans/:/usr/src/assistans/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=web_assistans
      - POSTGRES_PASSWORD=web_assistans
      - POSTGRES_DB=web_assistans_dev

volumes:
  postgres_data:
