# Generated by Django 3.2.9 on 2022-02-18 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='общая сумма')),
                ('_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='общая сумма')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_source', models.CharField(max_length=64, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('amount_source', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='общая сумма')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.budget')),
            ],
        ),
        migrations.CreateModel(
            name='Spent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='время')),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='сумма траты')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='время')),
                ('date_event', models.DateField(blank=True, default=None, null=True, verbose_name='время события')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='сумма траты')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='время')),
                ('amount_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='сумма добавления')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
