# Generated by Django 3.2.9 on 2022-01-31 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_expenseincome_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseincome',
            name='category',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category'),
        ),
        migrations.AlterField(
            model_name='expenseincome',
            name='date_event',
            field=models.DateField(blank=True, verbose_name='время события'),
        ),
    ]
