# Generated by Django 3.2.9 on 2022-01-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_expenseincome_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseincome',
            name='date_event',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='время события'),
        ),
    ]
