# Generated by Django 3.2.9 on 2022-02-04 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_expenseincome_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseincome',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category'),
        ),
    ]
