# Generated by Django 3.2.9 on 2022-02-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_expenseincome_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='общая сумма'),
        ),
    ]
