# Generated by Django 3.2.9 on 2022-02-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_budget__total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='main_budget',
            field=models.BooleanField(default=False),
        ),
    ]
